---
title: Do Lower Instructional Expenditures Lead to Higher 4-Year Public High School Graduation Rates in the U.S.?
author: "Larry Hernandez"
date: "May 5, 2016"
output: html_document
---
## Introduction
  With the national public high school 4-year adjusted cohort graduation rate (ACGR) in the United States residing at 81.4% $^{\dag}$, with the lowest rate of 71.7% held by Georgia and the highest rate of 89.7% claimed by Iowa, it is no surprise that many people would like to direct more money into the public education system. After all, it is commonly thought that more money in schools will translate into increased student achievement, and in particular more graduates. Educational expenses that are often targeted by this frame of thought include instructional supplies, instructional services, and teacher compensation, collectively known as instructional expenditures.  
    
  But does increased spending on instruction lead to higher 4-year public high school graduation rates? Some would argue yes. Instructional supplies and services are extremely important to student learning since they are part of the foundation of classroom education. More money for supplies and services would ensure that all students are set up for a successful learning experience. And perhaps paying teachers higher wages-or simply giving them annual bonuses for yielding higher standardized test scores-will increase their effectiveness as educators. A higher paid teacher could focus more on her curriculum instead of working a second, part-time job to make ends meet. While this theory seems plausible, the contrary theory seems reasonable too and is the hypothesis of this paper. Lower instructional expenditures per student may actually lead to higher 4-year ACGRs in U.S. public high school districts, because lower instructional expenditures would require schools to be innovative with their curricula in ways that promote student achievement and also require schools to employ the types of teachers who are willing to get paid lower salaries.

## Methods
  In this investigation, we study the relationship between 4-year ACGR and instructional expenditures per student in public high school districts across forty eight of the fifty states, including the District of COlumbia. We take into account demographic and financial variables related to education systems, including racial composition of a school, percentage of students identified as English language learners, and percentage of students receiving free or reduced lunch. Using a multiple linear regression analysis, we examine the hypothesis that low instructional expenditures per student lead to higher 4-year ACGR in US public high schools.  
  
### Data Sources
  Data used in this study was obtained from the National Center for Education Statistics (NCES) and the U.S. Department of Education EDFacts Initiative (EDFacts) websites. All data reflect the 2012-2013 school year for school districts residing in the United States, including the District of Columbia, and are indexed with a unique Local Education Agency Identification (LEAID) number. URLs are provided in the Appendix at the end of this document.

  Since it is common for some students to change school districts throughout their high school experience, the 4-year adjusted cohort graduation rate (ACGR) is the version of high school graduation rate that is studied in this investigation. The ACGR accounts for student mobility, including transfers, emigration, and death during the 4-year academic period. ACGR is considered to be an accurate estimate of 4-year graduation rates. These data are found on the EdFacts website.
    
  The primary predictor of interest in this investigation is Instructional Expenditure per Student. Instructional expenditures include costs for instructional supplies, instructional services, and teacher salaries and benefits. The data for this variable is provided by the Elementary / Secondary Information System (ElSi) tableGenerator tool on the National Center for Education Statistics website.
    
  Other variables that are included in this investigation are: Urban Centric Locale; student-teacher ratio; number of students classified as English Language Learners (ELL); numbers of Hispanic, Asian / Pacific Islander, White, Black, and First Nations students; total student enrollment; and number of students eligible for free or reduced lunch, by school district. Urban Centric Locale indicates if a school district resides in a city (small, medium, or large), a suburb, a town, or rural area. Eligibility for reduced or free lunch is utilized as a proxy for poverty. These data are found on the NCES website using the Elsi tableGenerator.
        
  It should be noted that the Idaho state education agency was not required to calculate or report the new four-year ACGR for academic year 2012-13. Therefore, data corresponding to districts residing in Idaho were not available and, consequently, those districts were excluded from this study.
  
### Data Cleaning
  The aforementioned data were cleaned and transformed for analysis. Some ACGR data were provided in the form of a range, such as 60-69, or were anonymized as a code, such as "GT50", representing a value "greater than 50 percent". Records with ACGR values reported as a range greater than 5 (percent) were excluded in order to minimize the impact of these data on the final model since most ACGR values were greater than 60. The counts for each racial group were transformed to percentages of the student body, as were the counts for English Language Learners, and the counts for students in the reduced lunch program.
        
  Only districts containing all of the desired predictors were included in the final analysis. Since the Alabama education agency did not report statistics on the number of English Language Learners for any of its school districts, all school districts residing in Alabama were incidentally omitted from this study.
    
### Statistical Techniques
  A multiple linear regression (MLR) model was fit to the ACGR data while controlling for percentage of students eligible for free or reduced lunch, student-teacher ratio, percentage of English Language Learners, percentage of students from non-White, non-Asian racial backgrounds, and urban centric locale:
    
  The MLR model was chosen since these types of models generally perform reasonably well at capturing relationships between variables of interest, even those that are nonlinear, and are well-suited for interpretation, the primary goal of this work. The specific predictors chosen here were readily available and some have suspected to be related to high school graduation rates. The model was fit on a random 20% sample of the data set, and using this fit, the mean squared prediction error was calculated on the remaining 80% of the data. To test the model against perturbation, it was fit on california data and used to predict wisconsin ACGR.
    
  A nonparametric bootstrap with 1,000 iterations was performed to estimate the coefficient for Instructional Expenditures per Student and the intercept term. This same bootstrap was used to obtain estimates for the standard deviations of these coefficients. The nonparametric version was utilized since the true underlying relationship between the predictors and outcome are likely not linear. 
    
## Results
  The summary of the estimated coefficients for this MLR model (Table 1) indicates p-values that are nearly zero for Instructional Expenditures and most of the other predictors, suggesting statistically significant relationships between these predictors and the outcome. The Adjusted R-squared value of 0.38 indicates that 38% of the variation is explained by the  model. The estimated coefficient for the primary predictor, Instructional Expenditures, is -0.001 with a standard error of 1.18e-4, and a highly significant p-value smaller than 2e-16. The intercept, which describes the average graduation rate for White or Asian students from large cities is 115%, with a variance of 2.6%. This value for the intercept is clearly bogus and indicates problems with this model.
    
  The nonparametric bootstrap yielded a value of -0.001075 for Instructional Expenditures, in agreement with the value reported in Table 1, and a standard deviation of 0.00013, which is smaller than that reported in Table 1. The p-value for this estimated coefficient is too small to measure, which is consistent with the value reported in Table 1. The bootstrap estimates for the intercept term and standard deviation are , respectively. The associated p-value is again too small to measure and is consistent with the nearly-zero value reported in Table 1.
    
  A plot of the Residuals vs Fitted ACGR Values (Figure 1) reveals that the model suffers from non-constant variance since it contains a leftward-facing fan-shaped pattern. The Q-Q plot (Figure 2) reveals violation of normality of the errors, since the data deviate from the straight line, particularly on the ends. The spatial plot of the predicted values for ACGR (Figure 3) reveals problems with the model. Some of the predicted values are negative and some exceed 100%. These are unrealistic values for graduation rates.
  The mean squared prediction error when the model is run on the validation set is 63%, which is substantially large. The mean squared prediction error was 29% for Wisconsin data when the model was fit using only the California data. This is a large error but not surprising considering the model has major problems.
  
  The spatial plot of the residuals reveals that neighboring districts exhibit similar residual values, indicating a violation of the assumption that the covariance of the error is zero. This is not surprising since neighboring districts would share similar student demographics.

## Conclusion
  Unfortunately, the final model chosen for this data set suffered from high variance, as indicated by the funnel shape in FIgure ??, and leads to mean squared error of 63%. Despite efforts to transform several of the variables, including logarithmic transformations, square roots, reciprocal of the outcome, and several combinations of these transformations on the outcome and predictors of interest, the least unsatisfactory model obtaind was the one provided here. Additionally, utilizing generalized additive models did not appear helpful. Additionally, technological issues related to mapping the data (with Shapefiles) made diagnosis challenging. Thus, with the modeling process still in need of refinement, no claim can be made at this time about the relationship between Instructional Expenditures per Student and ACGR. The hypothesis remains to be tested.
    
  There were several limitations of this study which affect the results and analysis. A first limitation is the lack of potentially useful, confounding variables that could impact ACGR. Some of these variables are behavior and crime statistics in schools, attendance rates, availability of college-readiness programs such as Gear-Up, access to programs that help struggling students, participation in extracurricular activities, preparedness for high school upon completion of middle school or other measure of academic achievement at the start of 9th grade, educational attainment of parental guardian(s), to name a few. Many of these variables are available in the School Survey on Crime and Safety (SSOCS) for various years or the High School Longitudinal Study of 2009, but access to those data are excluded to qualified education researchers. A second limitation is the quality of the data used for the analysis. Data that is more complete or specific could lead to improved analysis. For example, one-third of the ACGR values were either completely anonymized or reported as a range of values (i.e, 60-69; 50+; 80+; below 50), where the reported ACGR ranges were largest for the smallest schools and visa-versa. Third, since these data were collected as part of a survey, there is randomness associated with reporting that include data entry errors, incorrectly quoted values due to misunderstanding survey questions, non-respondents (i.e. Idaho) or missing values for predictors used in this study (i.e. Alabama). Finally, had a more satisfactory model been found, inferences about individual students could not be made using the results provided by the model, as this would constitute ecological (inference) fallacy. Any correlations found using these aggregated data from school populations cannot be imposed upon any individual student.
        
  Given additional variables and time to conduct the corresponding analysis, a better assessment of the relationship between ACGR and Instructional Expenditures per student could potentially be determined.

## Appendix
The following is a list of the data sources and corresponding URLs for the predictors used in this study.

[1] Adjusted Cohort Graduate Rates for School Year 2012-2013:
http://www2.ed.gov/about/inits/ed/edfacts/data-files/acgr-lea-sy2012-13.csv

[2] NCES 2013 Data for Income and Poverty:
http://nces.ed.gov/programs/edge/tables.aspx?ds=acsProfile&y=2013

[3] ElSi tableGenerator data:
http://nces.ed.gov/ccd/elsi/tableGenerator.aspx?savedTableID=16594
http://nces.ed.gov/ccd/elsi/tableGenerator.aspx?savedTableID=36934

```{r, echo=FALSE, warning=FALSE}
# Clear workspace
rm(list=ls())

# For reproducibility
set.seed(1)

# Load libraries and functions with R script
source("load_libraries_functions.R")

# Load school district data from disk with R script
source("load_project_data.R")

# Aggregate and clean the data. The dataframe of interest after this step is called 'ed_data'
source("aggregate_and_clean_data.R")

# Define predictors of interest
#predictors = c("FIPST","leaid12","acgr","InstrExpend","StudentTeacher","income","White","UrbanLocale","Latitude","Longitude")

cols_for_model = c("STNAM","FIPST","leaid12","acgr","InstrExpend","StudentTeacher","income","White","pctELL","UrbanLocale","Latitude","Longitude")

features = c("acgr","InstrExpend","StudentTeacher","income","White","pctELL","UrbanLocale","Latitude","Longitude")

cols_for_tableau = c("STNAM","FIPST","LEANM","leaid12","acgr", "InstrExpend","income","WhiteCount","BlackCount","AsianPacificCount","HispanicCount","FirstNationsCount", "MultiRacialCount","TotalRace","White","nonWhite","under_minority","StudentTeacher","pctELL","Lunch","UrbanLocale","Latitude","Longitude")

# Extract predictors of interest
modeling_data = ed_data[,cols_for_model]
#source("leaflet_test.R")

# Write data to csv
#output_csv = "C:/Users/Larry/graduation_rates/clean_ed_data.csv"
#write.csv(ed_data[,cols_for_tableau],file=output_csv)


# Scale graduation rates to reside between 0 and 1
#modeling_data$acgr = modeling_data$acgr / 100
#modeling_data$pctELL = modeling_data$pctELL / 100
#modeling_data$White = modeling_data$White / 100

# Divide the data set into (1) training set and (2) validation set
proportion_of_data_as_training = 0.20
indices_for_training = get_indices_for_training_set(modeling_data, proportion_of_data_as_training)
training_data = modeling_data[indices_for_training,]
validation_data = get_test_set(modeling_data,indices_for_training)

########################################################################################## ##########################################################################################
##################                                             ###########################
################## Create statistical model & make predictions ###########################
##################                                             ###########################
##########################################################################################
##########################################################################################
#### NOTE: LOOK INTO USING THE 'under_rep_minority' VARIABLE INSTEAD OF 'White'; ALSO CONSIDER USING OTHER VARIABLES ####

x11();
plot(modeling_data$InstrExpend,modeling_data$acgr, xlab ="Instructional Expenditures Per Student", ylab = "ACGR")

x11();
plot(modeling_data$income / 50000,modeling_data$acgr, xlab ="Median Income", ylab = "ACGR")

x11();
plot(training_data$income / 50000,training_data$acgr / 100, xlab ="Median Income", ylab = "ACGR", col='yellow')
x = seq(1.05,5,.025)
y = 1.15 + 1/(1-(x+2))
points(x,y,col='blue')
print(max(y))

 dx = 0.05
 x = seq(1+dx,5,dx)
 y = log(x-1)
 x11();
 plot(x,log(x-1)+1,col='red')
 points(x,log10(x-1)+1,col='blue')
 points(x,logb(x-1,100)+1,col='pink')
 points(x,logb(x-1,2)+1,col='green')
 # 

 x11();
# plot(x,y,col='red')
# points(x,log10(x-1),col='blue')
 y = (logb(x-1,100)+1)
 c = 1/max(y)
 
 y2 = (logb(x-1,100)+1)
 c2 = 1 #/max(y2)
 plot(x,c*y,col='green')
 points(x,c2*y2,col='red')
 points(training_data$income/50000,training_data$acgr / 100, xlab ="Median Income", ylab = "ACGR", col='black')

##################################################################################
################################  Logarithmic estimate  ########################## ##################################################################################

 log_est = lm(acgr~ log(income), data = training_data)
summary(log_est)
log_pred = predict(log_est, training_data)


x11();
plot(training_data$income,training_data$acgr, xlab ="Median Income", ylab = "ACGR",pch = 20, col='red')
x = sort(training_data$income)
curve(coef(log_est)[1] + coef(log_est)[2]*log(x),add=TRUE,col=4, lwd=4)
title(main = "Income vs ACGR with logarithmic fit")

log_est2 = lm(acgr~ log(income) + InstrExpend, data = training_data)
summary(log_est2)
log_pred2 = predict(log_est2, training_data)


log_estn = lm(acgr~ log(income) + InstrExpend + White, data = training_data)
summary(log_estn)
predictions = predict(log_estn, validation_data)
validation_mse = mean( (predictions - validation_data$acgr)^2, na.rm = TRUE)


######################################## Hyperbola estimate ########################################
hyperbola_est = lm(acgr ~ 1/(1-income), data = training_data)
hyperbola_pred = predict(hyperbola_est, training_data)
b = coef(hyperbola_est)[1]
m = coef(hyperbola_est)[2]
x11();
plot(x, b + 1.16/(1-x),col=4, lwd=4)
#plot(training_data$income,training_data$acgr, xlab ="Median Income", ylab = "ACGR", pch = 20, col='black')
#curve(b + m*1/(x),add=TRUE,col=4, lwd=4)
title(main = "Income vs ACGR with hyperbolic fit")


lin_model_2 = glm(acgr~ InstrExpend + income - leaid12 - FIPST, data = training_data)
summary(lin_model_2)

lin_model_3 = glm(acgr~ InstrExpend + income + White - leaid12 - FIPST, data = training_data)
summary(lin_model_3)

lin_model_4 = glm(acgr~ InstrExpend + income + White + StudentTeacher - leaid12 - FIPST, data = training_data)
summary(lin_model_4)

lin_model_5 = glm(acgr~ InstrExpend + income + White + StudentTeacher - leaid12 - FIPST, data = training_data)
summary(lin_model_5)

lin_model_6 = glm(acgr~ InstrExpend + income + White + StudentTeacher + UrbanLocale - leaid12 - FIPST, data = training_data)
summary(lin_model_6)

# Predict on validation set, calculate prediction error
acgr_predictions = predict(lin_model, validation_data)
validation_mse = mean( (acgr_predictions - validation_data$acgr)^2, na.rm = TRUE)

# Cross validation error (to compare with)
cv.error.10 = cv.glm(ed_data,ed_model,K=10)$delta[1]

########################### Non-Parametric Bootstrap  #########################
#n <- nrow(training_data)    ## number of observations
n <- nrow(modeling_data)    ## number of observations
B <- 1000                   ## number of bootstrap samples
#set.seed(1)
nonpara.bootstrap.ests <- numeric(B)
nonpara.bootstrap.b0 <- numeric(B)

for(i in 1:B)
{
  bootstrap.inds <- sample(n, n, TRUE)
  mod.boot <- lm(acgr[bootstrap.inds] ~ InstrExpend[bootstrap.inds] + StudentTeacher[bootstrap.inds] +       
              income[bootstrap.inds] + White[bootstrap.inds] + UrbanLocale[bootstrap.inds], data=modeling_data)
  betas.star <- coef(mod.boot)
  nonpara.bootstrap.ests[i] <- betas.star[2]
  nonpara.bootstrap.b0[i] <- betas.star[1]
}

# Plot Nonparametric bootstrap of Beta1 (i.e. Coefficient of Instructional Expenditures)
x11()
nonpara_hist = hist(nonpara.bootstrap.ests, main = expression(paste("Nonparametric Bootstrap Dist. of Instructional Expenditures*")), xlab = expression(paste('Instructional Expenditures',', ',hat(beta)[1],'*')))
center = mean(nonpara.bootstrap.ests)
height_at_center = 300
abline(v = center, col = 2, lwd=2)
segments(center, height_at_center/2, center + sd(nonpara.bootstrap.ests), height_at_center/2, col = "darkgreen", lwd=2)
legend("topright", c(expression(paste(hat(beta)[1],'*')), expression(paste("SE(", hat(beta)[1], "*)"))), bty="n", lwd=2, col=c("red", "darkgreen", "white"))

# calculate p-value of beta1 (i.e. Coefficient of Instructional Expenditures)
if (center > 0){
  p_value_nonpara_boot = sum(nonpara.bootstrap.ests < 0) / B
  }else{
  p_value_nonpara_boot = sum(nonpara.bootstrap.ests > 0) / B
  }
sd_b1 = sd(nonpara.bootstrap.ests)
p_value_b1 = pt(mean(nonpara.bootstrap.ests) / sd_b1, B-2)*2


# Plot Nonparametric bootstrap of Intercept (i.e. Grad Rates of non-White students in large cities)
x11()
nonpara_hist = hist(nonpara.bootstrap.b0, main = expression(paste("Nonparametric Bootstrap Dist. of Intercept*")), xlab = expression(paste('Intercept',', ',hat(beta)[0],'*')))
center = mean(nonpara.bootstrap.b0)
height_at_center = 300
abline(v = center, col = 2, lwd=2)
segments(center, height_at_center/2, center + sd(nonpara.bootstrap.b0), height_at_center/2, col = "darkgreen", lwd=2)
legend("topright", c(expression(paste(hat(beta)[0],'*')), expression(paste("SE(", hat(beta)[0], "*)"))), bty="n", lwd=2, col=c("red", "darkgreen", "white"))

# Estimate p-value of intercept
if (center > 0){
   p_value_nonpara_boot = sum(nonpara.bootstrap.b0 < 0) / B
}else{
  p_value_nonpara_boot = sum(nonpara.bootstrap.b0 > 0) / B
}

sd_b0 = sd(nonpara.bootstrap.b0)
print(sd_b0)
p_value_b0 = pt(mean(nonpara.bootstrap.b0) / sd_b0, B-2)*2

######## Sandwich estimation for variance & p-values due to heteroskedasticity #######

# intercept
coeff_index = 1
variance_b0 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b0))

# InstrExpend
coeff_index = 2
variance_b1 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b1))

# StudentTeacher
coeff_index = 3
variance_b2 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b2))

# income
coeff_index = 4
variance_b3 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b3))

# White
coeff_index = 5
variance_b4 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b4))

# UrbanLocale12-City: Mid-size 
coeff_index = 6    # 7-16 yield results for other levels of UrbanLocale
variance_b5 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b5))

# Interaction(Latitude,Longitude)
coeff_index = 17    # 7-16 yield results for other levels of UrbanLocale
variance_b17 = vcovHC(ed_model, type = "HC")[coeff_index,coeff_index]
dnorm(ed_model$coef[coeff_index]/sqrt(variance_b17))


#################### Spatial Maps ####################
# Load Unified School Districts: California
shape_file_unified_ca <-"C:/Users/Larry/Desktop/Shapefiles/from_government_site/california/tl_2013_06_unsd_extracted/tl_2013_06_unsd.shp"
sh_unified_ca <- readShapePoly(shape_file_unified_ca)
 
# Load Secondary School District Polygons: California
shape_file_secondary_ca <-"C:/Users/Larry/Desktop/Shapefiles/from_government_site/california/tl_2015_06_scsd_extracted/tl_2015_06_scsd.shp"
sh_secondary_ca <- readShapePoly(shape_file_secondary_ca)

# Extract CA data & Visualize Measured & Predicted ACGR as well as residuals
ca_indices      = which(modeling_data$FIPST == 6)
ca_data         = modeling_data[ca_indices,]
ca_data_to_plot = subset(modeling_data[ca_indices,],select=c("leaid12","acgr"))
sh_ca_secondary_with_acgr <- merge_data_with_shape(sh_secondary_ca,ca_data_to_plot,"GEOID","leaid12")
sh_ca_unified_with_acgr   <- merge_data_with_shape(sh_unified_ca, ca_data_to_plot,"GEOID","leaid12")
x11()
map_ssd_unsd_acgr(sh_secondary_ca,sh_unified_ca,ca_data,modeling_data, title_content="CA")


ca_map <-leaflet(sh_ca_unified_with_acgr) %>%
#  addPolygons(
#    stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5,
#    color = ~colorQuantile("YlOrRd", #sh_ca_unified_with_acgr$acgr)(acgr)
#  ) %>%
  addPolygons(
    stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5,
    color = ~colorQuantile("YlOrRd", sh_ca_secondary_with_acgr$acgr)(acgr)
  )

ca_map

#map_shape_file(sh_ca_secondary_with_acgr, ca_data$acgr, ca_data$leaid12, acgr_title, add_plot = FALSE)
#map_shape_file(sh_ca_unified_with_acgr,ca_data$acgr, ca_data$leaid12, acgr_title, add_plot = TRUE)

#wi_indices      = which(modeling_data$FIPST == 55)
#wi_data_to_plot = subset(modeling_data[wi_indices,],select=c("leaid12","acgr"))

#ed_data_to_plot = subset(modeling_data,select=c("leaid12","acgr"))
# sh_secondary_with_acgr <- merge_data_with_shape(shape_secondary,ed_data_to_plot,"GEOID","leaid12")
# sh_unified_with_acgr   <- merge_data_with_shape(shape_unified, ed_data_to_plot,"GEOID","leaid12")

##### Subset the acgr data
# ed_data_to_plot = subset(modeling_data,select=c("leaid12","acgr"))
# sh_secondary_with_acgr <- merge_data_with_shape(shape_secondary,ed_data_to_plot,"GEOID","leaid12")
# sh_unified_with_acgr   <- merge_data_with_shape(shape_unified, ed_data_to_plot,"GEOID","leaid12")

# map_ssd_unsd_acgr(sh_secondary_wi,sh_unified_wi,wi_data_to_plot,lm.model_ca, title_content="WI")

################################################ Various plots #########################################################

# Map outcome of interest (i.e. acgr)
# x11()
# acgr_title = "Measured Adj. Cohort Grad. Rates"
# map_shape_file(sh_secondary_with_acgr, modeling_data$acgr, modeling_data$leaid12, acgr_title, add_plot = FALSE)
# map_shape_file(sh_unified_with_acgr,modeling_data$acgr, modeling_data$leaid12, acgr_title, add_plot = TRUE)


# Map predicted values of acgr
# x11()
# predicted_acgr = predict.lm(ed_model,modeling_data)
# pred_title = "Predicted Adj. Cohort Grad. Rates"
# map_shape_file(sh_secondary_with_acgr, predicted_acgr, modeling_data$leaid12, pred_title, add_plot = FALSE)
# map_shape_file(sh_unified_with_acgr, predicted_acgr, modeling_data$leaid12, pred_title, add_plot = TRUE)

# 
# # Map residuals
# x11()
# title = "Residuals"
# map_shape_file(sh_secondary_with_acgr, ed_model$residuals, modeling_data$leaid12, title, add_plot = FALSE)
# map_shape_file(sh_unified_with_acgr, ed_model$residuals, modeling_data$leaid12, title, add_plot = TRUE)

# Map a few variables of interest: income, InstrExpend, StudentTeacher, pctELL
#x11()
#title = "Median Household Income"
#map_shape_file(sh_secondary_with_acgr, modeling_data$income, modeling_data$leaid12, title, add_plot = FALSE)
#map_shape_file(sh_unified_with_acgr, modeling_data$income, modeling_data$leaid12, title, add_plot = TRUE)
#dev.off()

#x11()
#title = "Instructional Expenditures Per Student"
#map_shape_file(sh_secondary_with_acgr, modeling_data$InstrExpend, modeling_data$leaid12, title, add_plot = FALSE)
#map_shape_file(sh_unified_with_acgr, modeling_data$InstrExpend, modeling_data$leaid12, title, add_plot = TRUE)
#dev.off()

#x11()
#title = "Percentage of Students who are English Language Learners"
#map_shape_file(sh_secondary_with_acgr,modeling_data$pctELL, modeling_data$leaid12, title, add_plot = #FALSE)
#map_shape_file(sh_unified_with_acgr, modeling_data$pctELL, modeling_data$leaid12, title, add_plot = #TRUE)
#dev.off()
```