# Load relevant libraries
library(varhandle)
library(boot)
library(leaps)
library(sp)
library(maptools)
library(RColorBrewer)
library(classInt)
library(tree)
library(akima)
library(splines)
library(foreach)
library(sandwich)
library(leaflet)
library(magrittr)
library(maps)
library(htmltools)
library(rgdal) # to reading/writing geo shapefiles
library(rgeos) # for shapefile simplification


# Load user defined functions
source("convert_income_id_to_integer.R")
source("is.letter.R")
source("process_rate.R")
source("process_special_rate_codes.R")
source("median_of_numerical_range_represented_as_char.R")
source("convert_numeric_factor_to_integer.R")
source("convert_numeric_factor_to_numeric.R")
source("number_of_na_values.R")
source("merge_data_with_shape.R")
source("map_ssd_unsd_acgr.R")
source("map_shape_file.R")
source("get_indices_for_training_set.R")
source("get_test_set.R")
source("determine_imputed_numeric_value.R")
source("fill_with_median.R")
source("fill_missing_values_by_category.R")
source("impute_missing_values.R")
source("fill_na_with_value.R")
source("remove_records.R")
source("linear_scale.R")
source("scale_df_column.R")
source("plot2columns.R")