# Load relevant libraries
library(varhandle)
library(boot)
library(leaps)
library(sp)
library(maptools)
library(RColorBrewer)
library(classInt)
library(gam)
library(akima)
library(splines)
library(foreach)
library(mgcv)

# Load user defined functions
source("convert_income_id_to_integer.R")
source("is.letter.R")
source("process_rate.R")
source("process_special_rate_codes.R")
source("median_of_numerical_range_represented_as_char.R")
source("convert_numeric_factor_to_integer.R")
source("convert_numeric_factor_to_numeric.R")
source("number_of_na_values.R")
source("merge_data_with_shape.R")
source("map_shape_file.R")
source("get_indices_for_training_set.R")
source("get_test_set.R")